##db configuration
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
#spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=film;encrypt=true;trustServerCertificate=true;
#spring.datasource.username=spring
#spring.datasource.password=123
#  # Auto Update
#spring.jpa.hibernate.ddl-auto=update
#server.port=8080
#spring.jpa.show-sql=true
#logging.level.org.hibernate.SQL=DEBUG

server:
  port: 8080

#db configuration
spring:
  datasource:
    url: "jdbc:sqlserver://localhost:1433;databaseName=film;encrypt=true;trustServerCertificate=true;"
    driver-class-name: "com.microsoft.sqlserver.jdbc.SQLServerDriver"
    username: spring
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "ZcCAeQKy0ly5bPdCVHM8bLQp5KJX9eczTqZl7zhjzK42U7SXfALZcWpSjitA5tLX"
  valid-duration: 3600 # in second
  refreshable-duration: 36000 # in seconds



